"""Shared dataclass carried by every rewriter.

Ideação 2cf21a31.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class RewriteResult:
    """Output of a QueryRewriter.

    Attributes:
        strategy: The strategy that was actually applied. May differ
            from the caller's request when a rewriter degrades
            gracefully (e.g. decompose called with a query the LLM
            declared non-composite returns strategy='none').
        original_query: The query the caller passed in, preserved for
            audit and for the downstream retrieve that may need it
            (HyDE retrieves with the original query but a custom
            embedding seed).
        rewritten_queries: Ordered tuple of queries to dispatch. Size
            1 for 'none' and 'hyde' (the same original query), N for
            'decompose' and 'fusion'.
        hyde_passage: The hypothetical passage generated by HyDE. None
            for every other strategy.
    """

    strategy: str
    original_query: str
    rewritten_queries: tuple[str, ...] = field(default_factory=tuple)
    hyde_passage: str | None = None
