"""Pure domain policy/predicate leaves (no DB/session/SQLAlchemy imports).

Modules here are safe to import from models, services and the bug-regression
resolver/gate without pulling heavy database dependencies.
"""

from okto_pulse.core.domain.entities import Board, Ideation, Spec
from okto_pulse.core.domain.entity_export import (
    ENTITY_EXPORT_BUNDLE_CONTRACT_VERSION,
    ENTITY_EXPORT_MANIFEST_CONTRACT_VERSION,
    ENTITY_EXPORT_SECTION_CONTRACT_VERSION,
    EntityExportBundle,
    EntityExportContractError,
    EntityExportDisclosure,
    EntityExportHistoryScope,
    EntityExportManifest,
    EntityExportOverallState,
    EntityExportRequest,
    EntityExportSection,
    EntityExportSectionManifestEntry,
    EntityExportSectionStatus,
    EntityExportSubjectSnapshot,
    EntityExportType,
)
from okto_pulse.core.domain.knowledge_governance import (
    KnowledgeGovernanceInvalidMetadata,
    KnowledgeGovernanceMetadataV1,
    normalize_knowledge_governance_metadata,
    parse_knowledge_governance_metadata,
    project_knowledge_governance,
)
from okto_pulse.core.domain.realm import (
    LOCAL_REALM_ID,
    MissingRealmScope,
    RealmIsolationViolation,
    RealmScope,
    require_realm_scope,
)
from okto_pulse.core.domain.spec_dependency import (
    SpecDependencyBlocker,
    SpecDependencyCapabilities,
    SpecDependencyDirection,
    SpecDependencyLifecycleFilter,
    SpecDependencyLineageFilter,
    SpecDependencyListItem,
    SpecDependencyListQuery,
    SpecDependencyMutationReceipt,
    SpecDependencyOperationError,
    SpecDependencyPage,
    SpecDependencyReadiness,
    SpecDependencyRecord,
    SpecDependencySatisfactionFilter,
    SpecDependencySpecSnapshot,
    spec_current_edition_started,
    spec_dependency_blocked_guidance,
    spec_dependency_blocking_facts,
    spec_dependency_cycle_path,
    spec_dependency_is_satisfied,
    spec_dependency_readiness_projection,
    spec_dependency_would_create_cycle,
    transition_starts_card_execution,
    transition_starts_spec_execution,
)

__all__ = [
    "Board",
    "ENTITY_EXPORT_BUNDLE_CONTRACT_VERSION",
    "ENTITY_EXPORT_MANIFEST_CONTRACT_VERSION",
    "ENTITY_EXPORT_SECTION_CONTRACT_VERSION",
    "EntityExportBundle",
    "EntityExportContractError",
    "EntityExportDisclosure",
    "EntityExportHistoryScope",
    "EntityExportManifest",
    "EntityExportOverallState",
    "EntityExportRequest",
    "EntityExportSection",
    "EntityExportSectionManifestEntry",
    "EntityExportSectionStatus",
    "EntityExportSubjectSnapshot",
    "EntityExportType",
    "Ideation",
    "KnowledgeGovernanceInvalidMetadata",
    "KnowledgeGovernanceMetadataV1",
    "LOCAL_REALM_ID",
    "MissingRealmScope",
    "RealmIsolationViolation",
    "RealmScope",
    "Spec",
    "SpecDependencyBlocker",
    "SpecDependencyCapabilities",
    "SpecDependencyDirection",
    "SpecDependencyLifecycleFilter",
    "SpecDependencyLineageFilter",
    "SpecDependencyListItem",
    "SpecDependencyListQuery",
    "SpecDependencyMutationReceipt",
    "SpecDependencyOperationError",
    "SpecDependencyPage",
    "SpecDependencyReadiness",
    "SpecDependencyRecord",
    "SpecDependencySatisfactionFilter",
    "SpecDependencySpecSnapshot",
    "normalize_knowledge_governance_metadata",
    "parse_knowledge_governance_metadata",
    "project_knowledge_governance",
    "require_realm_scope",
    "spec_current_edition_started",
    "spec_dependency_blocked_guidance",
    "spec_dependency_blocking_facts",
    "spec_dependency_cycle_path",
    "spec_dependency_is_satisfied",
    "spec_dependency_readiness_projection",
    "spec_dependency_would_create_cycle",
    "transition_starts_card_execution",
    "transition_starts_spec_execution",
]
