"""Deterministic projection of an authored capture; no semantic inference."""

from dataclasses import dataclass
from datetime import datetime

from okto_pulse.core.ports.kg_cognitive_source import CognitiveSourceRecord


LEARNING_CAPTURE_CANDIDATE_ID = 'authored-learning-capture'


def same_authored_timestamp(left, right) -> bool:
    """Compare zoned instants without rewriting the immutable authored value.

    Graph codecs may render UTC as Z; the source ledger keeps the original.
    Missing or naive timestamps never qualify as equivalent.
    """
    try:
        values = [datetime.fromisoformat(value.replace('Z', '+00:00')) for value in (left, right)]
        return all(value.utcoffset() is not None for value in values) and values[0] == values[1]
    except (AttributeError, TypeError, ValueError):
        return False


def learning_capture_projection_fields(capture: CognitiveSourceRecord) -> dict:
    """Keep the structured source immutable; show its scope in graph context.

    The graph's existing context property carries context plus applicability.
    Both original fields remain separately readable in the capture history.
    No title/lesson is generated by an LLM or inferred from an execution report.
    """
    payload = capture.payload
    return dict(title=f"Learning from Bug {payload['source']['bug_id']}",
        content=payload['content'],
        context=payload['context'] + '\n\nApplicability:\n' + payload['applicability'],
        justification='', source_artifact_ref=f"bug:{payload['source']['bug_id']}",
        graph_layer='canonical', maturity_status='canonical_eligible',
        source_content_hash=capture.record_fingerprint)


@dataclass(frozen=True)
class CapturedLearningProjection:
    """Internal commit input after relational revalidation in the same UOW."""

    capture: CognitiveSourceRecord
    head: CognitiveSourceRecord
    bug_id: str

    @property
    def node_id(self) -> str:
        return self.capture.node_id

    @property
    def fields(self) -> dict:
        return learning_capture_projection_fields(self.capture)

    @property
    def evidence_refs(self) -> tuple[str, ...]:
        return tuple(dict.fromkeys((*self.capture.evidence_refs, f'bug:{self.bug_id}')))

    def require_authored_graph_fields(self, attrs) -> None:
        wanted = {**self.fields, 'created_by_agent': self.capture.payload['author_id'],
            'generation': self.capture.generation}
        if (any(attrs.get(key) != value for key, value in wanted.items())
                or not same_authored_timestamp(attrs.get('created_at'), self.capture.payload['captured_at'])
                or attrs.get('human_curated') or attrs.get('superseded_by')
                or attrs.get('revocation_reason')):
            raise ValueError('learning_materialization_projection_conflict')

    def require_literal_head(self) -> None:
        if self.head.record_fingerprint == self.capture.record_fingerprint:
            return
        if ((self.head.board_id, self.head.node_type, self.head.node_id, self.head.generation)
                != (self.capture.board_id, 'Learning', self.node_id, self.capture.generation)
                or self.head.source_revision <= self.capture.source_revision
                or self.head.evidence_refs != self.evidence_refs
                or 'capture_format' in self.head.payload):
            raise ValueError('learning_materialization_projection_conflict')
        self.require_authored_graph_fields(self.head.payload)
