"""Compatibility port for the embedded board graph runtime.

This port exists only for legacy surfaces that still expose the historical
``kg.schema`` API. New business code should prefer the narrower graph ports
(``GraphTransaction``, ``CypherExecutor``, ``GraphLifecycle`` and friends).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class BoardGraphRuntime(Protocol):
    """Edition-owned implementation of the legacy board graph runtime API."""

    def board_kuzu_path(self, board_id: str) -> Path: ...

    def bootstrap_board_graph(self, board_id: str) -> Any: ...

    def ensure_board_graph_bootstrapped(self, board_id: str) -> None: ...

    def open_board_connection(self, board_id: str) -> Any: ...

    def open_board_connection_raw(self, board_id: str) -> Any: ...

    def close_all_connections(self, board_id: str | None = None) -> None: ...

    def close_board_db_cache(self, board_id: str | None = None) -> None: ...

    def purge_board_graph_storage(self, board_id: str, *, reason: str = "manual") -> list[str]: ...

    def migrate_schema_for_board(self, board_id: str) -> bool: ...

    def reset_bootstrap_cache_for_tests(self) -> None: ...

    def apply_ladybug_lifecycle_step(self, *args: Any, **kwargs: Any) -> Any: ...

    def load_vector_extension(self, conn: Any) -> None: ...

    def open_kuzu_db(self, path: Path) -> Any: ...

    def new_connection(self, db: Any) -> Any: ...

    def is_ladybug_corruption_error(self, exc: BaseException) -> bool: ...

