"""Lazy exports for transport schemas and domain enums."""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:  # real imports for static analysis only — never run at import
    from okto_pulse.core.domain.enums import (
        CardPriority,
        CardStatus,
        IdeationComplexity,
        IdeationStatus,
        RefinementStatus,
        SpecStatus,
        StoryStatus,
        SprintStatus,
    )
    from okto_pulse.core.models.schemas import (
        ActivityLogResponse,
        AgentBoardOverridesUpdate,
        AgentBoardResponse,
        AgentCreate,
        AgentRevealResponse,
        AgentResponse,
        AgentSummary,
        AgentUpdate,
        ArchitectureDesignCreate,
        ArchitectureDesignResponse,
        ArchitectureDesignSummary,
        ArchitectureDesignUpdate,
        ArchitectureDiagram,
        ArchitectureDiagramPayloadRef,
        ArchitectureDiagramPayloadResponse,
        ArchitectureDiffResponse,
        ArchitectureEntity,
        ArchitectureInterface,
        AttachmentResponse,
        AttachmentUpload,
        BaseSchema,
        BoardCreate,
        BoardListResponse,
        BoardResponse,
        BoardShareCreate,
        BoardShareResponse,
        BoardShareUpdate,
        BoardSummary,
        BoardUpdate,
        CardCreate,
        CardMove,
        CardResponse,
        CardSummary,
        CardUpdate,
        CommentCreate,
        CommentResponse,
        CommentUpdate,
        ErrorResponse,
        IdeationCreate,
        IdeationHistoryResponse,
        IdeationKnowledgeCreate,
        IdeationKnowledgeResponse,
        IdeationKnowledgeSummary,
        IdeationKnowledgeUpdate,
        IdeationMove,
        IdeationQAAnswer,
        IdeationQACreate,
        IdeationQAResponse,
        IdeationResponse,
        IdeationSummary,
        IdeationUpdate,
        PaginatedResponse,
        QACreate,
        QAAnswer,
        QAResponse,
        RefinementCreate,
        RefinementHistoryResponse,
        RefinementKnowledgeCreate,
        RefinementKnowledgeResponse,
        RefinementKnowledgeSummary,
        RefinementMove,
        RefinementQAAnswer,
        RefinementQACreate,
        RefinementQAResponse,
        RefinementResponse,
        RefinementSnapshotResponse,
        RefinementSnapshotSummary,
        RefinementSummary,
        RefinementUpdate,
        SpecCreate,
        SpecKnowledgeCreate,
        SpecKnowledgeResponse,
        SpecKnowledgeSummary,
        SpecHistoryResponse,
        SpecKnowledgeUpdate,
        SpecMove,
        SpecQAAnswer,
        SpecQACreate,
        SpecQAResponse,
        SpecResponse,
        SpecSummary,
        SpecUpdate,
        StoryConversionRequest,
        StoryConversionResponse,
        StoryCreate,
        StoryIdeationLinkResponse,
        StoryLinkCreate,
        StoryMove,
        StoryResponse,
        StorySummary,
        StoryUpdate,
        SprintCreate,
        SprintEvaluationCreate,
        SprintHistoryResponse,
        SprintMove,
        SprintQAAnswer,
        SprintQACreate,
        SprintQAResponse,
        SprintResponse,
        SprintSummary,
        SprintUpdate,
        TopicCreate,
        TopicResponse,
        TopicSummary,
        TopicUpdate,
    )

# name -> defining submodule, resolved lazily on first access.
_ENUM_NAMES = (
    "CardPriority",
    "CardStatus",
    "IdeationComplexity",
    "IdeationStatus",
    "RefinementStatus",
    "SpecStatus",
    "StoryStatus",
    "SprintStatus",
)
_SCHEMA_NAMES = (
    "ActivityLogResponse",
    "AgentBoardOverridesUpdate",
    "AgentBoardResponse",
    "AgentCreate",
    "AgentRevealResponse",
    "AgentResponse",
    "AgentSummary",
    "AgentUpdate",
    "ArchitectureDesignCreate",
    "ArchitectureDesignResponse",
    "ArchitectureDesignSummary",
    "ArchitectureDesignUpdate",
    "ArchitectureDiagram",
    "ArchitectureDiagramPayloadRef",
    "ArchitectureDiagramPayloadResponse",
    "ArchitectureDiffResponse",
    "ArchitectureEntity",
    "ArchitectureInterface",
    "AttachmentResponse",
    "AttachmentUpload",
    "BaseSchema",
    "BoardCreate",
    "BoardListResponse",
    "BoardResponse",
    "BoardShareCreate",
    "BoardShareResponse",
    "BoardShareUpdate",
    "BoardSummary",
    "BoardUpdate",
    "CardCreate",
    "CardMove",
    "CardResponse",
    "CardSummary",
    "CardUpdate",
    "CommentCreate",
    "CommentResponse",
    "CommentUpdate",
    "ErrorResponse",
    "IdeationCreate",
    "IdeationHistoryResponse",
    "IdeationKnowledgeCreate",
    "IdeationKnowledgeResponse",
    "IdeationKnowledgeSummary",
    "IdeationKnowledgeUpdate",
    "IdeationMove",
    "IdeationQAAnswer",
    "IdeationQACreate",
    "IdeationQAResponse",
    "IdeationResponse",
    "IdeationSummary",
    "IdeationUpdate",
    "PaginatedResponse",
    "QACreate",
    "QAAnswer",
    "QAResponse",
    "RefinementCreate",
    "RefinementHistoryResponse",
    "RefinementKnowledgeCreate",
    "RefinementKnowledgeResponse",
    "RefinementKnowledgeSummary",
    "RefinementMove",
    "RefinementQAAnswer",
    "RefinementQACreate",
    "RefinementQAResponse",
    "RefinementResponse",
    "RefinementSnapshotResponse",
    "RefinementSnapshotSummary",
    "RefinementSummary",
    "RefinementUpdate",
    "SpecCreate",
    "SpecKnowledgeCreate",
    "SpecKnowledgeResponse",
    "SpecKnowledgeSummary",
    "SpecHistoryResponse",
    "SpecKnowledgeUpdate",
    "SpecMove",
    "SpecQAAnswer",
    "SpecQACreate",
    "SpecQAResponse",
    "SpecResponse",
    "SpecSummary",
    "SpecUpdate",
    "StoryConversionRequest",
    "StoryConversionResponse",
    "StoryCreate",
    "StoryIdeationLinkResponse",
    "StoryLinkCreate",
    "StoryMove",
    "StoryResponse",
    "StorySummary",
    "StoryUpdate",
    "SprintCreate",
    "SprintEvaluationCreate",
    "SprintHistoryResponse",
    "SprintMove",
    "SprintQAAnswer",
    "SprintQACreate",
    "SprintQAResponse",
    "SprintResponse",
    "SprintSummary",
    "SprintUpdate",
    "TopicCreate",
    "TopicResponse",
    "TopicSummary",
    "TopicUpdate",
)

_SOURCE: dict[str, str] = {}
for _n in _ENUM_NAMES:
    _SOURCE[_n] = "okto_pulse.core.domain.enums"
for _n in _SCHEMA_NAMES:
    _SOURCE[_n] = "okto_pulse.core.models.schemas"


def __getattr__(name: str):
    module = _SOURCE.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(importlib.import_module(module), name)
    globals()[name] = value  # cache so subsequent access skips __getattr__
    return value


def __dir__() -> list[str]:
    return sorted(__all__)


__all__ = [
    # Domain enums
    "CardPriority",
    "CardStatus",
    "IdeationComplexity",
    "IdeationStatus",
    "RefinementStatus",
    "SpecStatus",
    "StoryStatus",
    "SprintStatus",
    # Schemas
    "ActivityLogResponse",
    "AgentBoardOverridesUpdate",
    "AgentBoardResponse",
    "AgentCreate",
    "AgentRevealResponse",
    "AgentResponse",
    "AgentSummary",
    "AgentUpdate",
    "ArchitectureDesignCreate",
    "ArchitectureDesignResponse",
    "ArchitectureDesignSummary",
    "ArchitectureDesignUpdate",
    "ArchitectureDiagram",
    "ArchitectureDiagramPayloadRef",
    "ArchitectureDiagramPayloadResponse",
    "ArchitectureDiffResponse",
    "ArchitectureEntity",
    "ArchitectureInterface",
    "AttachmentResponse",
    "AttachmentUpload",
    "BaseSchema",
    "BoardCreate",
    "BoardListResponse",
    "BoardResponse",
    "BoardShareCreate",
    "BoardShareResponse",
    "BoardShareUpdate",
    "BoardSummary",
    "BoardUpdate",
    "CardCreate",
    "CardMove",
    "CardResponse",
    "CardSummary",
    "CardUpdate",
    "CommentCreate",
    "CommentResponse",
    "CommentUpdate",
    "ErrorResponse",
    "IdeationCreate",
    "IdeationHistoryResponse",
    "IdeationKnowledgeCreate",
    "IdeationKnowledgeResponse",
    "IdeationKnowledgeSummary",
    "IdeationKnowledgeUpdate",
    "IdeationMove",
    "IdeationQAAnswer",
    "IdeationQACreate",
    "IdeationQAResponse",
    "IdeationResponse",
    "IdeationSummary",
    "IdeationUpdate",
    "PaginatedResponse",
    "QACreate",
    "QAAnswer",
    "QAResponse",
    "RefinementCreate",
    "RefinementHistoryResponse",
    "RefinementKnowledgeCreate",
    "RefinementKnowledgeResponse",
    "RefinementKnowledgeSummary",
    "RefinementMove",
    "RefinementQAAnswer",
    "RefinementQACreate",
    "RefinementQAResponse",
    "RefinementResponse",
    "RefinementSnapshotResponse",
    "RefinementSnapshotSummary",
    "RefinementSummary",
    "RefinementUpdate",
    "SpecCreate",
    "SpecKnowledgeCreate",
    "SpecKnowledgeResponse",
    "SpecKnowledgeSummary",
    "SpecHistoryResponse",
    "SpecKnowledgeUpdate",
    "SpecMove",
    "SpecQAAnswer",
    "SpecQACreate",
    "SpecQAResponse",
    "SpecResponse",
    "SpecSummary",
    "SpecUpdate",
    "StoryConversionRequest",
    "StoryConversionResponse",
    "StoryCreate",
    "StoryIdeationLinkResponse",
    "StoryLinkCreate",
    "StoryMove",
    "StoryResponse",
    "StorySummary",
    "StoryUpdate",
    "SprintCreate",
    "SprintEvaluationCreate",
    "SprintHistoryResponse",
    "SprintMove",
    "SprintQAAnswer",
    "SprintQACreate",
    "SprintQAResponse",
    "SprintResponse",
    "SprintSummary",
    "SprintUpdate",
    "TopicCreate",
    "TopicResponse",
    "TopicSummary",
    "TopicUpdate",
]
