"""Backend runtime ports (spec #15, card 72bcdfcf).

Pure Protocol contracts + DTOs for the runtime boundary: settings persistence,
scheduler control, runtime control and runtime/observability events. No concrete
framework, persistence, scheduler or transport import at runtime.
"""

from __future__ import annotations

from .data_bootstrapper import (
    BOOTSTRAP_DOMAINS,
    BootstrapDomain,
    DataBootstrapError,
    DataBootstrapPlan,
    DataBootstrapResult,
    DataBootstrapStatus,
    DataBootstrapStep,
    DataBootstrapStepResult,
    DataBootstrapper,
    require_bootstrapper,
)
from .content_ingestion import (
    ContentIngestionError,
    ContentIngestionResolver,
    IngestedBinaryContent,
    IngestedTextContent,
)
from .coordination import (
    ClaimRepository,
    ConfigValidationPort,
    CoordinationProviderMissing,
    LeaseHandle,
    LeaseProvider,
    RuntimeSettingsProvider,
    WriteLockHandle,
    WriteLockPort,
    get_claim_repository,
    get_config_validation_port,
    get_lease_provider,
    get_runtime_settings_provider,
    get_write_lock_port,
    register_coordination_providers,
    reset_coordination_providers_for_tests,
)
from .mcp_auth import (
    MCP_AUTH_FAILURE_REASONS,
    MCP_CREDENTIAL_SOURCES,
    AgentAuthSession,
    AuthSession,
    McpAuthenticator,
    McpAuthError,
    McpAuthFailureReason,
    McpCredential,
    McpCredentialSource,
    mcp_credential_from_sources,
    require_authenticator,
)
from .mcp_trace import McpTraceRecord, McpTraceSink, TraceWriteResult
from .relational_schema_migrator import (
    MIGRATION_PHASES,
    MigrationPhase,
    MigrationPlan,
    MigrationResult,
    MigrationStatus,
    MigrationStep,
    MigrationStepResult,
    RelationalSchemaMigrator,
    SchemaMigrationError,
    StepStatus,
    require_migrator,
)
from .capability_descriptor import (
    CapabilityDescriptor,
    CapabilityDescriptorSource,
    capability_scope_violations,
    classify_resources,
    descriptors_to_dicts,
)
from .mcp_resources import (
    CompositeMcpResourceCatalog,
    McpResourceCatalog,
    McpResourceSpec,
    StaticMcpResourceCatalog,
    catalog_link_integrity,
    catalog_uri_conflicts,
    scan_forbidden_terms,
)
from .runtime_control import RuntimeCompositionLike, RuntimeControl
from .runtime_events import RuntimeEvent, RuntimeEventBusPort
from .runtime_settings import (
    KG_TICK_RESCHEDULE_FAILED_SIGNAL,
    RESCHEDULE_FAILED_FORBIDDEN_FIELDS,
    RESCHEDULE_FAILED_REQUIRED_FIELDS,
    ActorContextLike,
    RuntimeEffectResult,
    RuntimeSettingsPort,
    RuntimeSettingsSnapshot,
    build_reschedule_failed_signal,
    sanitize_message,
)
from .scheduler import (
    KG_DAILY_TICK_JOB_ID,
    SchedulerControl,
    SchedulerResult,
)
from .telemetry import (
    HEALTH_REPORT_FIELDS,
    PRODUCT_AGGREGATE_FAMILIES,
    PRODUCT_METRIC_KEYS,
    HealthReport,
    ProductAggregationPort,
    ProductState,
    PublishHealthSource,
    TelemetryEventStore,
    TelemetryPort,
    TelemetryResult,
    TelemetrySink,
    TelemetryState,
    TelemetryStateCarrier,
    TelemetryStateStore,
)

__all__ = [
    "HEALTH_REPORT_FIELDS",
    "PRODUCT_AGGREGATE_FAMILIES",
    "PRODUCT_METRIC_KEYS",
    "ClaimRepository",
    "ConfigValidationPort",
    "CoordinationProviderMissing",
    "ContentIngestionError",
    "ContentIngestionResolver",
    "HealthReport",
    "IngestedBinaryContent",
    "IngestedTextContent",
    "LeaseHandle",
    "LeaseProvider",
    "ProductAggregationPort",
    "ProductState",
    "PublishHealthSource",
    "TelemetryPort",
    "TelemetryResult",
    "TelemetrySink",
    "TelemetryState",
    "TelemetryStateCarrier",
    "TelemetryStateStore",
    "TelemetryEventStore",
    "TraceWriteResult",
    "ActorContextLike",
    "AgentAuthSession",
    "AuthSession",
    "CapabilityDescriptor",
    "CapabilityDescriptorSource",
    "capability_scope_violations",
    "classify_resources",
    "descriptors_to_dicts",
    "CompositeMcpResourceCatalog",
    "McpResourceCatalog",
    "McpResourceSpec",
    "StaticMcpResourceCatalog",
    "catalog_link_integrity",
    "catalog_uri_conflicts",
    "scan_forbidden_terms",
    "BOOTSTRAP_DOMAINS",
    "BootstrapDomain",
    "DataBootstrapError",
    "DataBootstrapPlan",
    "DataBootstrapResult",
    "DataBootstrapStatus",
    "DataBootstrapStep",
    "DataBootstrapStepResult",
    "DataBootstrapper",
    "KG_DAILY_TICK_JOB_ID",
    "MCP_AUTH_FAILURE_REASONS",
    "MCP_CREDENTIAL_SOURCES",
    "McpAuthError",
    "McpAuthFailureReason",
    "McpAuthenticator",
    "McpCredential",
    "McpCredentialSource",
    "McpTraceRecord",
    "McpTraceSink",
    "mcp_credential_from_sources",
    "require_authenticator",
    "KG_TICK_RESCHEDULE_FAILED_SIGNAL",
    "MIGRATION_PHASES",
    "MigrationPhase",
    "MigrationPlan",
    "MigrationResult",
    "MigrationStatus",
    "MigrationStep",
    "MigrationStepResult",
    "RESCHEDULE_FAILED_FORBIDDEN_FIELDS",
    "RESCHEDULE_FAILED_REQUIRED_FIELDS",
    "RelationalSchemaMigrator",
    "RuntimeCompositionLike",
    "RuntimeControl",
    "RuntimeEffectResult",
    "RuntimeEvent",
    "RuntimeEventBusPort",
    "RuntimeSettingsPort",
    "RuntimeSettingsProvider",
    "RuntimeSettingsSnapshot",
    "SchedulerControl",
    "SchedulerResult",
    "SchemaMigrationError",
    "StepStatus",
    "WriteLockHandle",
    "WriteLockPort",
    "build_reschedule_failed_signal",
    "get_claim_repository",
    "get_config_validation_port",
    "get_lease_provider",
    "get_runtime_settings_provider",
    "get_write_lock_port",
    "require_bootstrapper",
    "require_migrator",
    "register_coordination_providers",
    "reset_coordination_providers_for_tests",
    "sanitize_message",
]
