"""Backend runtime ports (spec #15, card 72bcdfcf).

Pure Protocol contracts + DTOs for the runtime boundary: settings persistence,
scheduler control, runtime control and runtime/observability events. No concrete
framework, persistence, scheduler or transport import at runtime.
"""

from __future__ import annotations

import importlib

from .data_bootstrapper import (
    BOOTSTRAP_DOMAINS,
    BootstrapDomain,
    DataBootstrapError,
    DataBootstrapPlan,
    DataBootstrapResult,
    DataBootstrapStatus,
    DataBootstrapStep,
    DataBootstrapStepResult,
    DataBootstrapper,
    require_bootstrapper,
)
from .content_ingestion import (
    ContentIngestionError,
    ContentIngestionResolver,
    IngestedBinaryContent,
    IngestedTextContent,
)
from .coordination import (
    ClaimRepository,
    ConfigValidationPort,
    CoordinationProviderMissing,
    LeaseHandle,
    LeaseProvider,
    RuntimeSettingsProvider,
    WriteLockHandle,
    WriteLockPort,
    get_claim_repository,
    get_config_validation_port,
    get_lease_provider,
    get_runtime_settings_provider,
    get_write_lock_port,
    register_coordination_providers,
    reset_coordination_providers_for_tests,
)
from .mcp_auth import (
    MCP_AUTH_FAILURE_REASONS,
    MCP_CREDENTIAL_SCOPE_KEY,
    MCP_CREDENTIAL_SOURCES,
    AgentAuthSession,
    AuthSession,
    McpAuthenticator,
    McpAuthError,
    McpAuthFailureReason,
    McpCredential,
    McpCredentialSource,
    mcp_credential_from_sources,
    principal_from_auth_session,
    require_authenticator,
)
from .authentication import (
    AuthenticationError,
    AuthenticationPort,
    AuthorizationDenied,
    Credential,
    InvalidCredential,
    MissingCredential,
    Principal,
)
from .mcp_instructions import (
    McpInstructionProvider,
    StaticMcpInstructionProvider,
)
from .mcp_trace import McpTraceRecord, McpTraceSink, TraceWriteResult
from .mcp_host import (
    McpHostProvider,
    McpHostProviderMissing,
    get_mcp_host_provider,
    register_mcp_host_provider,
    reset_mcp_host_provider_for_tests,
)
from .relational_schema_migrator import (
    MIGRATION_PHASES,
    MigrationPhase,
    MigrationPlan,
    MigrationResult,
    MigrationStatus,
    MigrationStep,
    MigrationStepResult,
    RelationalSchemaMigrator,
    SchemaMigrationError,
    StepStatus,
    require_migrator,
)
from .relational_effects import (
    ConsolidationQueueUpsert,
    KGTickRunUpsert,
    RelationalEffectsPort,
    RelationalEffectsProviderMissing,
    get_relational_effects_port,
    register_relational_effects_port,
    reset_relational_effects_port_for_tests,
)
from .kg_operational import (
    KGCanonicalDebtSignal,
    KGDeadLetterSignal,
    KGGovernanceEffectsPort,
    KGOperationalProviderMissing,
    KGOperationalReadModelPort,
    KGOutboxCounts,
    KGQueueEntrySnapshot,
    KGWorkerAuditPort,
    KGWorkerQueuePort,
    get_kg_governance_effects_port,
    get_kg_operational_read_model_port,
    get_kg_worker_audit_port,
    get_kg_worker_queue_port,
    register_kg_operational_ports,
    reset_kg_operational_ports_for_tests,
)
from .kg_events import (
    HISTORICAL_PROGRESS_SETTINGS_KEY,
    KGEventsPoll,
    KGEventsProviderMissing,
    KGEventsReaderPort,
    KGOutboxEvent,
    get_kg_events_reader_port,
    register_kg_events_reader_port,
    reset_kg_events_reader_port_for_tests,
)
from .kg_cognitive_source import (
    CognitiveSourceError,
    CognitiveSourceRecord,
    CognitiveSourceStore,
    register_cognitive_source_store,
    require_cognitive_source_store,
    reset_cognitive_source_store_for_tests,
    resolve_cognitive_source_store,
)
from .kg_equivalence_ledger import (
    EquivalenceLedger,
    EquivalenceLedgerError,
    EquivalenceRecord,
    register_equivalence_ledger,
    require_equivalence_ledger,
    reset_equivalence_ledger_for_tests,
    resolve_equivalence_ledger,
)
from .kg_subtype_registry import (
    NodeSubtypeRegistry,
    SubtypeDeclaration,
    SubtypeRegistryError,
    register_node_subtype_registry,
    require_node_subtype_registry,
    reset_node_subtype_registry_for_tests,
    resolve_node_subtype_registry,
    validate_subtype_declaration,
)
from .relational_runtime import (
    RelationalDatabasePathUnavailable,
    close_db,
    configure_database_runtime,
    get_engine,
    get_session_factory,
    init_db,
    is_database_runtime_configured,
    reset_database_runtime_for_tests,
    resolve_sqlite_database_path,
)
from .relational_application import (
    AgentAuthenticationGateway,
    AgentPermissionContext,
    EffectivePermissions,
    PermissionPresetGateway,
    PermissionPresetView,
    RelationalApplicationAdapter,
    RelationalApplicationAdapterMissing,
    register_relational_application_adapter,
    reset_relational_application_adapter_for_tests,
    require_relational_application_adapter,
)
from .permission_policy import (
    builtin_preset_name,
    flatten_permission_flags,
    get_permission_flag,
    legacy_permissions_to_flags,
    resolve_effective_permissions,
    set_permission_flag,
)
from .capability_descriptor import (
    CapabilityDescriptor,
    CapabilityDescriptorSource,
    capability_scope_violations,
    classify_resources,
    descriptors_to_dicts,
)
from .mcp_resources import (
    CompositeMcpResourceCatalog,
    McpResourceCatalog,
    McpResourceSpec,
    StaticMcpResourceCatalog,
    catalog_link_integrity,
    catalog_uri_conflicts,
    scan_forbidden_terms,
)
from .package_version import (
    ImportlibMetadataVersionProvider,
    MappingPackageVersionProvider,
    PackageVersionProvider,
)
from .runtime_control import RuntimeCompositionLike, RuntimeControl
from .runtime_events import RuntimeEvent, RuntimeEventBusPort
from .runtime_settings import (
    KG_TICK_RESCHEDULE_FAILED_SIGNAL,
    RESCHEDULE_FAILED_FORBIDDEN_FIELDS,
    RESCHEDULE_FAILED_REQUIRED_FIELDS,
    ActorContextLike,
    RuntimeEffectResult,
    RuntimeSettingsPort,
    RuntimeSettingsSnapshot,
    build_reschedule_failed_signal,
    sanitize_message,
)
from .runtime_workers import (
    RuntimeWorkerRegistry,
    RuntimeWorkerSpec,
    RuntimeWorkerStartFailure,
    RuntimeWorkerStopFailure,
)
from .scheduler import (
    JobSpec,
    KG_DAILY_TICK_JOB_ID,
    SchedulerControl,
    SchedulerJobHandler,
    SchedulerJobSnapshot,
    SchedulerResult,
)
from .telemetry import (
    HEALTH_REPORT_FIELDS,
    PRODUCT_AGGREGATE_FAMILIES,
    PRODUCT_METRIC_KEYS,
    HealthReport,
    ProductAggregationPort,
    ProductState,
    PublishHealthSource,
    TelemetryEventStore,
    TelemetryEffectConfigProvider,
    TelemetryPort,
    TelemetryResult,
    TelemetrySink,
    TelemetryState,
    TelemetryStateCarrier,
    TelemetryStateStore,
)

__all__ = [
    "Base",
    "HEALTH_REPORT_FIELDS",
    "PRODUCT_AGGREGATE_FAMILIES",
    "PRODUCT_METRIC_KEYS",
    "ClaimRepository",
    "ConfigValidationPort",
    "CoordinationProviderMissing",
    "ContentIngestionError",
    "ContentIngestionResolver",
    "ConsolidationQueueUpsert",
    "Credential",
    "HealthReport",
    "ImportlibMetadataVersionProvider",
    "IngestedBinaryContent",
    "IngestedTextContent",
    "LeaseHandle",
    "LeaseProvider",
    "MappingPackageVersionProvider",
    "MissingCredential",
    "PermissionPresetGateway",
    "PermissionPresetView",
    "ProductAggregationPort",
    "PackageVersionProvider",
    "ProductState",
    "Principal",
    "PublishHealthSource",
    "TelemetryPort",
    "TelemetryResult",
    "TelemetrySink",
    "TelemetryState",
    "TelemetryStateCarrier",
    "TelemetryStateStore",
    "TelemetryEffectConfigProvider",
    "TelemetryEventStore",
    "TraceWriteResult",
    "ActorContextLike",
    "AgentAuthSession",
    "AgentAuthenticationGateway",
    "AgentPermissionContext",
    "AuthenticationError",
    "AuthenticationPort",
    "AuthSession",
    "AuthorizationDenied",
    "CapabilityDescriptor",
    "CapabilityDescriptorSource",
    "capability_scope_violations",
    "classify_resources",
    "descriptors_to_dicts",
    "CompositeMcpResourceCatalog",
    "McpInstructionProvider",
    "McpHostProvider",
    "McpHostProviderMissing",
    "McpResourceCatalog",
    "McpResourceSpec",
    "StaticMcpInstructionProvider",
    "StaticMcpResourceCatalog",
    "catalog_link_integrity",
    "catalog_uri_conflicts",
    "scan_forbidden_terms",
    "BOOTSTRAP_DOMAINS",
    "BootstrapDomain",
    "DataBootstrapError",
    "DataBootstrapPlan",
    "DataBootstrapResult",
    "DataBootstrapStatus",
    "DataBootstrapStep",
    "DataBootstrapStepResult",
    "DataBootstrapper",
    "CognitiveSourceError",
    "CognitiveSourceRecord",
    "CognitiveSourceStore",
    "EquivalenceLedger",
    "EquivalenceLedgerError",
    "EquivalenceRecord",
    "NodeSubtypeRegistry",
    "SubtypeDeclaration",
    "SubtypeRegistryError",
    "EffectivePermissions",
    "JobSpec",
    "KG_DAILY_TICK_JOB_ID",
    "KGTickRunUpsert",
    "KGCanonicalDebtSignal",
    "KGDeadLetterSignal",
    "KGEventsPoll",
    "KGEventsProviderMissing",
    "KGEventsReaderPort",
    "KGGovernanceEffectsPort",
    "KGOperationalProviderMissing",
    "KGOperationalReadModelPort",
    "KGOutboxCounts",
    "KGOutboxEvent",
    "KGQueueEntrySnapshot",
    "KGWorkerAuditPort",
    "KGWorkerQueuePort",
    "MCP_AUTH_FAILURE_REASONS",
    "MCP_CREDENTIAL_SCOPE_KEY",
    "MCP_CREDENTIAL_SOURCES",
    "McpAuthError",
    "McpAuthFailureReason",
    "McpAuthenticator",
    "McpCredential",
    "McpCredentialSource",
    "McpTraceRecord",
    "McpTraceSink",
    "InvalidCredential",
    "mcp_credential_from_sources",
    "principal_from_auth_session",
    "require_authenticator",
    "KG_TICK_RESCHEDULE_FAILED_SIGNAL",
    "MIGRATION_PHASES",
    "MigrationPhase",
    "MigrationPlan",
    "MigrationResult",
    "MigrationStatus",
    "MigrationStep",
    "MigrationStepResult",
    "RESCHEDULE_FAILED_FORBIDDEN_FIELDS",
    "RESCHEDULE_FAILED_REQUIRED_FIELDS",
    "RelationalApplicationAdapter",
    "RelationalApplicationAdapterMissing",
    "RelationalDatabasePathUnavailable",
    "RelationalSchemaMigrator",
    "RelationalEffectsPort",
    "RelationalEffectsProviderMissing",
    "RuntimeCompositionLike",
    "RuntimeControl",
    "RuntimeEffectResult",
    "RuntimeEvent",
    "RuntimeEventBusPort",
    "RuntimeWorkerRegistry",
    "RuntimeWorkerSpec",
    "RuntimeWorkerStartFailure",
    "RuntimeWorkerStopFailure",
    "RuntimeSettingsPort",
    "RuntimeSettingsProvider",
    "RuntimeSettingsSnapshot",
    "SchedulerControl",
    "SchedulerJobHandler",
    "SchedulerJobSnapshot",
    "SchedulerResult",
    "SchemaMigrationError",
    "StepStatus",
    "WriteLockHandle",
    "WriteLockPort",
    "build_reschedule_failed_signal",
    "builtin_preset_name",
    "flatten_permission_flags",
    "get_claim_repository",
    "get_config_validation_port",
    "get_engine",
    "get_permission_flag",
    "get_lease_provider",
    "get_relational_effects_port",
    "require_relational_application_adapter",
    "resolve_effective_permissions",
    "get_kg_governance_effects_port",
    "get_mcp_host_provider",
    "get_kg_events_reader_port",
    "get_kg_operational_read_model_port",
    "get_kg_worker_audit_port",
    "get_kg_worker_queue_port",
    "get_runtime_settings_provider",
    "get_session_factory",
    "get_write_lock_port",
    "legacy_permissions_to_flags",
    "close_db",
    "configure_database_runtime",
    "init_db",
    "is_database_runtime_configured",
    "require_bootstrapper",
    "require_migrator",
    "register_coordination_providers",
    "register_kg_operational_ports",
    "register_mcp_host_provider",
    "register_cognitive_source_store",
    "register_equivalence_ledger",
    "register_node_subtype_registry",
    "require_cognitive_source_store",
    "require_equivalence_ledger",
    "require_node_subtype_registry",
    "reset_cognitive_source_store_for_tests",
    "reset_equivalence_ledger_for_tests",
    "reset_node_subtype_registry_for_tests",
    "resolve_cognitive_source_store",
    "resolve_equivalence_ledger",
    "resolve_node_subtype_registry",
    "validate_subtype_declaration",
    "register_kg_events_reader_port",
    "register_relational_effects_port",
    "register_relational_application_adapter",
    "reset_coordination_providers_for_tests",
    "reset_database_runtime_for_tests",
    "reset_kg_operational_ports_for_tests",
    "reset_mcp_host_provider_for_tests",
    "reset_kg_events_reader_port_for_tests",
    "reset_relational_effects_port_for_tests",
    "reset_relational_application_adapter_for_tests",
    "resolve_sqlite_database_path",
    "sanitize_message",
    "set_permission_flag",
    "HISTORICAL_PROGRESS_SETTINGS_KEY",
]

_LAZY_EXPORTS = {
    "Base": "okto_pulse.core.ports.relational_runtime",
}


def __getattr__(name: str):
    module = _LAZY_EXPORTS.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(importlib.import_module(module), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *_LAZY_EXPORTS})
