"""Deterministic generator for the ``tools_catalog`` MCP resource.

The hand-maintained catalog drifted (audit 2026-07-12: 167 of 265 tools
listed, plus one phantom). The committed
``resources/reference/tools_catalog.md`` is now GENERATED by this module
and guarded by ``tests/test_mcp_tools_catalog_drift.py``, which renders
the catalog from the LIVE tool registry and asserts byte equality — any
tool added/removed/renamed turns the gate red until the catalog is
regenerated (and, when needed, classified below).

Regenerate with::

    python -m okto_pulse.core.mcp.tools_catalog_generator

Classification is an ORDERED first-match rule list. Every tool MUST land
in a section — the drift test fails on any unclassified tool, which is
the forcing function that keeps the catalog complete.  Documentation is
resolved independently from exact ``## `tool_name``` headings across all
tool-doc resources.  Missing or duplicate headings fail generation, so a
catalog entry can never point merely at a family file that does not document
that particular tool.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable

FRONTMATTER = '---\nversion: "1.0"\ngenerated_by: okto_pulse.core.mcp.tools_catalog_generator\n---\n'

HEADER = (
    "# Okto Pulse — MCP Tools Catalog\n\n"
    "GENERATED FILE — do not edit by hand. Regenerate with\n"
    "`python -m okto_pulse.core.mcp.tools_catalog_generator`\n"
    "(guarded by tests/test_mcp_tools_catalog_drift.py).\n\n"
    "Tool schemas arrive lazily via MCP `tools/list`. Every entry links the\n"
    "exact resource containing that tool's args, returns and examples.\n"
    "Required filters for the consolidated `list_*` tools:\n"
    "`okto-pulse://reference/list_tools`.\n"
    "Semantic guideline protocol:\n"
    "`okto-pulse://reference/policy-compliance`.\n"
)

# Ordered (section, tool-doc family or None, matcher) rules — FIRST match wins.
# Matchers are regexes on the full tool name.
_RULES: tuple[tuple[str, str | None, str], ...] = (
    # --- KG (most specific prefixes first) --------------------------------
    ("KG — Consolidation (write path)", "kg",
     r"^okto_pulse_kg_(begin|add_node|add_edge|propose|commit|abort)_"),
    ("KG — Query (Recall)", "kg",
     r"^okto_pulse_kg_(get_decision_history|get_related_context|get_supersedence_chain|"
     r"find_contradictions|find_similar_decisions|get_similar_nodes|explain_constraint|"
     r"list_alternatives|get_learning_from_bugs|query_global)$"),
    ("KG — Query (Power)", "kg",
     r"^okto_pulse_kg_(query_cypher|query_natural|query_reflective|schema_info|"
     r"verify_grounding|provenance_drift|export_jsonld)$"),
    ("KG — Cognitive readiness & closeout", "kg",
     r"^okto_pulse_kg_(evaluate_bug_cognitive_closure|evaluate_cognitive_readiness|"
     r"list_cognitive_dlq|list_cognitive_pending_items|list_cognitive_readiness_items|"
     r"update_cognitive_pending_item|record_cognitive_skip|clear_cognitive_skip)$"),
    ("KG — Rebuild & recovery", "kg",
     r"^okto_pulse_kg_(rebuild_preflight|rebuild_confirm|rebuild_run|quarantine_restore|"
     r"global_discovery_recovery_(preflight|confirm|run))$"),
    ("KG — Operational & health", "kg", r"^okto_pulse_kg_"),
    # --- Boards, agents & session -----------------------------------------
    ("Session & Agents", "agent",
     r"^okto_pulse_(get_my_profile|update_my_profile|list_agents|list_my_boards|"
     r"list_my_mentions|get_unseen_summary|mark_as_seen)$"),
    ("Boards & Governance", "board",
     r"^okto_pulse_(get_board$|list_board_members|get_activity_log|get_analytics|"
     r"get_publish_health|get_resource_gate_summary|mark_resource_not_applicable|"
     r"clear_resource_not_applicable|get_allowed_transitions)"),
    ("Default Board Config", "board",
     r"^okto_pulse_.*default_board_config|^okto_pulse_get_board_default_config_diff$"),
    ("Design Systems", "board",
     r"design_system"),
    ("Semantic Guideline Assessments & Exceptions", "guideline",
     r"^okto_pulse_(record_semantic_guideline_assessment(?:_v2)?|"
     r"list_semantic_guideline_assessments|"
     r"get_semantic_guideline_assessment|"
     r"get_current_semantic_guideline_assessment|"
     r"list_semantic_guideline_findings|"
     r"list_semantic_guideline_waivers|"
     r"get_semantic_guideline_waiver|"
     r"list_semantic_guideline_waiver_events|"
     r"(request|review|revoke|revalidate)_semantic_guideline_waiver)$"),
    ("Guidelines", "guideline",
     r"guideline"),
    # --- SDLC entities ------------------------------------------------------
    ("Stories & Topics", "story",
     r"(story$|stories|topic)"),
    ("Quality Assessments", "quality",
     r"^okto_pulse_(record_ambiguity_assessment|"
     r"get_current_quality_assessment|get_quality_assessment_receipt|"
     r"list_quality_assessments|list_quality_findings)$"),
    ("Ideations", "ideation",
     r"ideation"),
    ("Refinements", "refinement",
     r"refinement|research_decision"),
    ("Specs — lifecycle & gates", "spec",
     r"^okto_pulse_(create_spec|update_spec$|delete_spec$|move_spec|get_spec$|"
     r"get_spec_context|get_spec_history|derive_spec_from_ideation|"
     r"submit_spec_validation|list_spec_validations|submit_spec_evaluation|"
     r"get_spec_evaluation|list_spec_evaluations|delete_spec_evaluation|"
     r"get_checklist_binding|"
     r"start_checklist_execution|submit_checklist_execution|"
     r"get_checklist_receipt|"
     r"migrate_spec_decisions|update_spec_entity|remove_spec_entity|"
     r"update_spec_api_contract|get_spec_knowledge|add_spec_knowledge|"
     r"delete_spec_knowledge|get_spec_snapshot)"),
    ("Specs — entities (rules, decisions, contracts, requirements)", "spec",
     r"(business_rule|decision$|decisions$|api_contract|integration_requirement|"
     r"observability_requirement)"),
    ("Test Scenarios", "test-scenario",
     r"test_scenario|resolve_bug_regression_scenarios"),
    ("Cards & Tasks", "card",
     r"(^okto_pulse_(create_card|update_card|move_card|delete_card|get_card)|"
     r"card_dependency|card_dependencies|cards_by_status|card_knowledge|"
     r"^okto_pulse_(get_task_context|get_task_conclusions|get_task_validation|"
     r"submit_task_validation|list_task_validations|link_task|list_blockers)$|"
     r"copy_.*_to_card)"),
    ("Amendments", "card",
     r"amendment"),
    ("Sprints", "sprint",
     r"sprint"),
    ("Q&A", "qa",
     r"(^okto_pulse_ask|_question$|^okto_pulse_answer|choice|^okto_pulse_list_qa$)"),
    ("Knowledge", "knowledge",
     r"knowledge"),
    ("Mockups", "mockup",
     r"mockup"),
    ("Architecture", "architecture",
     r"architecture"),
    ("Comments & Attachments", "comment",
     r"(comment|attachment)"),
    ("Listing & Traceability", "misc",
     r"^okto_pulse_(list_by_board|list_snapshots|get_traceability_report|"
     r"get_ideation_snapshot|get_refinement_snapshot|archive_tree|restore_tree)$"),
)


def classify(name: str) -> tuple[str, str | None] | None:
    for section, family, pattern in _RULES:
        if re.search(pattern, name):
            return section, family
    return None


def unclassified(names: Iterable[str]) -> list[str]:
    return sorted(n for n in names if classify(n) is None)


_TOOL_HEADING = re.compile(r"^## `(?P<name>okto_pulse_[a-z0-9_]+)`\s*$", re.M)
_TOOL_DOC_URI_PREFIX = "okto-pulse://reference/tool-docs/"


def tool_doc_index() -> dict[str, str]:
    """Return exact tool → resource URI mapping; reject duplicate headings."""

    from okto_pulse.core.mcp import effective_resource_catalog

    found: dict[str, list[str]] = {}
    specs = sorted(
        (
            spec
            for spec in effective_resource_catalog().specs()
            if spec.uri.startswith(_TOOL_DOC_URI_PREFIX)
        ),
        key=lambda spec: spec.uri,
    )
    for spec in specs:
        for match in _TOOL_HEADING.finditer(spec.read()):
            found.setdefault(match.group("name"), []).append(spec.uri)
    duplicates = {name: uris for name, uris in found.items() if len(uris) != 1}
    if duplicates:
        detail = ", ".join(
            f"{name}={uris}" for name, uris in sorted(duplicates.items())
        )
        raise ValueError(f"duplicate tool-doc headings: {detail}")
    return {name: uris[0] for name, uris in found.items()}


def missing_tool_docs(
    names: Iterable[str], index: dict[str, str] | None = None
) -> list[str]:
    index = tool_doc_index() if index is None else index
    return sorted(set(names) - set(index))


def render_catalog(names: Iterable[str]) -> str:
    """Render the catalog text for the given LIVE tool names.

    Raises ``ValueError`` listing any unclassified tool — add one rule line
    to ``_RULES`` and regenerate (this is the anti-drift forcing function).
    """

    missing = unclassified(names)
    if missing:
        raise ValueError(
            "unclassified tools (add a _RULES entry): " + ", ".join(missing)
        )
    names = sorted(set(names))
    docs = tool_doc_index()
    undocumented = missing_tool_docs(names, docs)
    if undocumented:
        raise ValueError(
            "tools missing exact tool-doc heading: " + ", ".join(undocumented)
        )
    sections: dict[str, list[str]] = {}
    for name in names:
        section, _family = classify(name)  # type: ignore[misc]
        sections.setdefault(section, []).append(name)
    parts = [FRONTMATTER, HEADER]
    ordered = [s for s, _f, _p in _RULES]
    seen: set[str] = set()
    for section in ordered:
        if section in seen or section not in sections:
            continue
        seen.add(section)
        parts.append(f"\n## {section}\n")
        parts.extend(
            f"- `{name}` — docs: `{docs[name]}`\n"
            for name in sections[section]
        )
    return "".join(parts)


def _live_tool_names() -> list[str]:
    import asyncio

    from okto_pulse.core.mcp import server as _server

    tools = asyncio.run(_server.mcp.get_tools())
    return sorted(tools.keys())


def regenerate_file() -> str:
    """Rewrite resources/reference/tools_catalog.md from the live registry."""

    target = Path(__file__).parent / "resources" / "reference" / "tools_catalog.md"
    content = render_catalog(_live_tool_names())
    target.write_text(content, encoding="utf-8", newline="\n")
    return str(target)


if __name__ == "__main__":
    print(regenerate_file())
